name: POCT-PRODUCTION-poct.elabpro.in

on:
  workflow_dispatch:
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # or your preferred version

      - name: Install dependencies
        run: npm ci

      - name: Build React app
        run: npm run build
        
      - name: Copy via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          source: "dist/*"
          target: "/var/www/html/poct.elabpro.in/"
          host: ${{ secrets.REMOTE_HOST_POCT_PROD }}
          port: 22
          username: ${{ secrets.REMOTE_USER_POCT_PROD }}
          password: ${{ secrets.REMOTE_PASSWORD_POCT_PROD }}
          strip_components: 1
          overwrite: true
